### PR TITLE
Replace Underscore with Lodash

### LINKED ISSUE #187: Migrate to lodash
Should reduce our build size since we will only bundle the methods we use (which is quite few).

We could also play with the Lodash-webpack-plugin!

### PR DESCRIPTION
**Pull request by captbaritone**
Fixes #187

### CODE REVIEW

**Comment by captbaritone** [comment]
cc @jdalton because I know it will please him 😄

**Comment by jdalton** [comment]
To get the cherry-pick benefit you can either manually do it via:
```js
var find = require('lodash/find');
```
or jump on the ES6 train and use [babel-plugin-lodash](https://github.com/lodash/babel-plugin-lodash) which will do it for you.

**Comment by captbaritone** [comment]
@jdalton Yeah! I'm working on a PR to upgrade us to the current version of React, which will mean moving to Babel for jsx transpilation. Once we are using babel, I'm looking forward to using ES6+`babel-plugin-lodash`.

**Comment by jdalton** [comment]
Ok cool. Based on the usage here it looks like `lodash-webpack-plugin` will be a big build saver for ya.

**Comment by jdalton** [comment]
Though if you use it you'll want to use `_.find` + `_.matches` instead of enabling the 'shorthands' feature set.

**Comment by captbaritone** [comment]
Yeah, I've been following that project with interest. Pretty amazing work. We'll start with `babel-plugin-lodash` and go from there!

**Pull request merged**
