### PR TITLE
Log scraping errors to Sentry

### LINKED ISSUE #230: Integrate our non-flask code with Sentry
Looks like our Github plugin repo scraping task has been broken for several months, without us realizing it (#227).

It's currently not easy to tell when one of these tasks is crashing, unless you manually check the logs.

@jonafato Any interest in looking into this?

### PR DESCRIPTION
**Pull request by jonafato**
Sentry logging has already been added to the backend Flask and frontend
JavaScript components of the site. This change adds the same logging
integration to the daily scraping tasks.

Fixes #230.

### CODE REVIEW

**Comment by captbaritone** [comment]
Thanks!

Tests are failing for unrelated linting errors. I'll investigate that separately.

Code looks good to me. I'll give it a quick try this weekend before I merge/deploy.

**Comment by jonafato** [comment]
@captbaritone Looks like this was an update to flake8 that dropped backward compatibility a while back. #240 fixes the issue, and I'll rebase my changes here once that's merged.

**Comment by jonafato** [comment]
Rebased and passing tests. Let me know if you run into any issues when testing before deploying.

**Comment by captbaritone** [comment]
It looks like if we move the `Client` instantiations to the top of the files, we can capture all exceptions, not just the exceptions we are already handling.

For testing I created a file like this:

```
# test.py
from raven import Client
from secrets import SENTRY_DSN

client = Client(SENTRY_DSN)

x = 1 / 0
```

Running `python test.py` results in:

```
╭─[9:55]: jeldredge at tibbett-3558 in ~/p/vim-awesome on sentry*
╰─➤ python test.py
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    x = 1 / 0
ZeroDivisionError: integer division or modulo by zero
Sentry is attempting to send 1 pending error messages
Waiting up to 10 seconds
Press Ctrl-C to quit
```

And an exception in Sentry:

screen shot 2016-07-30 at 9 59 26 am

**Comment by jonafato** [comment]
@captbaritone Nice catch, updated.

**Pull request merged**
