### PR TITLE
Upgrade to RethinkDB 2.3.0

### PR DESCRIPTION
**Pull request by captbaritone**

### CODE REVIEW

**Comment by captbaritone** [comment]
FYI @dalanmiller

**Comment by dalanmiller** [comment]
Woohoo! Let me know if you need any help and how it goes.

**Comment by captbaritone** [comment]
@dalanmiller Thanks! Going to run the deploy now in https://gitter.im/vim-awesome/vim-awesome if you want to come hang out 😄

**Comment by captbaritone** [comment]
Done. Seems to have gone smoothly.

**Comment by thejsj** [comment]
Nice! Happy to see this make it in.

**Pull request merged**
